Text
std::string Text::m_text
Referenced by Draw, SetText, Update.
SDL_Color Text::m_color
Referenced by Draw, SetColor, Update.
Text::Text()
Text::~Text()
void Text::Start() override
void Text::Update(float deltaTime, Input input) override
Referenced by main.
void Text::Update(std::string newText, SDL_Color newColor)
References Draw, m_color, m_text.
void Text::Draw()
References GameObject::DrawTextColor, GameObject::m_alpha, m_color, GameObject::m_dimensions, GameObject::m_position, GameObject::m_renderer, GameObject::m_rotation, m_text, GameObject::m_texture.
Referenced by Update.
void Text::OnCollision(GameObject *collider) override
void Text::SetText(std::string newText)
References m_text.
Referenced by SM_Controller::OnCollision, SM_Controller::Update.
void Text::SetColor(SDL_Color newColor)
References m_color.