Game
std::vector<GameObject*> Game::m_activeScene
Referenced by AddObject, ClearScene, Draw, RemoveObject, SetActiveScene, Start, Update.
std::vector<std::vector<GameObject*>*> Game::m_scenes
Referenced by AddObject, AddSceneToGame, RemoveObject, SetActiveScene.
std::vector<AudioClip*> Game::m_audioClips
Referenced by ClearSounds, LoadSound, PlaySound, StopSound.
int Game::m_windowHeight
Referenced by Game, GetWindowSize, InitSystems.
int Game::m_windowWidth
Referenced by Game, GetWindowSize, InitSystems.
bool Game::m_isRunning
Referenced by Quit, Run.
Uint8 Game::m_activeSceneIndex
Referenced by GetActiveScene, SetActiveScene.
SDL_Window* Game::m_window
Referenced by InitSystems, ~Game.
SDL_Renderer* Game::m_renderer
Referenced by AddObject, Draw, InitSystems, ~Game.
double Game::m_deltaTime
Referenced by InitSystems, Run.
Game::Game()
Game::Game(int width, int height)
References m_windowHeight, m_windowWidth.
Game::~Game()
References ClearScene, ClearSounds, m_renderer, m_window.
Referenced by main.
bool Game::InitSystems()
References m_deltaTime, m_renderer, m_window, m_windowHeight, m_windowWidth.
Referenced by main.
void Game::Run()
References Draw, Input::keyboardState, MouseStateDescriptor::lPressed, m_deltaTime, m_isRunning, Input::mouseState, MouseStateDescriptor::rPressed, Start, Update, MouseStateDescriptor::x, MouseStateDescriptor::y.
Referenced by main.
glm::vec2 Game::GetWindowSize()
References m_windowHeight, m_windowWidth.
Referenced by SM_Controller::GetMovementArea, ObstacleCar::GetMovementArea, main, SM_Controller::Start, ObstacleCar::Start, ObstacleCar::Update, SM_Controller::Update.
void Game::AddObject(GameObject *object, int sceneIndex)
References m_activeScene, m_renderer, m_scenes.
Referenced by ObstacleMng::AddObstacle, main.
void Game::RemoveObject(std::string name, int sceneIndex)
References m_activeScene, m_scenes.
Referenced by SM_Controller::OnCollision, ObstacleCar::Update.
void Game::ClearScene()
References m_activeScene.
Referenced by ~Game.
void Game::AddSceneToGame()
References m_scenes.
Referenced by main.
void Game::SetActiveScene(int sceneIndex)
References m_activeScene, m_activeSceneIndex, m_scenes, Start.
Referenced by main, SM_Controller::OnCollision, ButtonTexture::Update.
Uint8 Game::GetActiveScene()
References m_activeSceneIndex.
Referenced by ButtonTexture::Update.
void Game::ClearSounds()
References m_audioClips.
Referenced by ~Game.
void Game::LoadSound(std::string name, std::string path)
References m_audioClips, AudioClip::m_clip, AudioClip::m_name.
Referenced by main.
void Game::PlaySound(std::string name, bool loop)
References m_audioClips.
Referenced by main, SM_Controller::OnCollision, ButtonTexture::Update.
void Game::StopSound(std::string name)
References m_audioClips.
Referenced by SM_Controller::OnCollision, ButtonTexture::Update.
void Game::Quit()
References m_isRunning.
Referenced by SM_Controller::Update.
void Game::Start()
References m_activeScene.
Referenced by Run, SetActiveScene.
void Game::Update(double delta, Input in)
References m_activeScene, GameObject::m_dimensions, GameObject::m_position, GameObject::OnCollision.
Referenced by Run.
void Game::Draw()
References DrawText, m_activeScene, m_renderer.
Referenced by Run.
void Game::DrawText()
Referenced by Draw.