SM_Controller
Text* SM_Controller::m_scoreText
Referenced by AssignTextScore, OnCollision, Update.
int SM_Controller::m_score
Referenced by GetScore, Start, Update.
int SM_Controller::m_highScore
Referenced by OnCollision, ReadFromFile, SetHighScore.
int SM_Controller::m_movX
Referenced by GetMovementArea.
float SM_Controller::m_time
Referenced by Update.
SM_Controller::SM_Controller()
SM_Controller::~SM_Controller()
void SM_Controller::Start() override
References Game::GetWindowSize, GameObject::m_dimensions, GameObject::m_game, GameObject::m_position, m_score, ReadFromFile.
void SM_Controller::Update(float deltaTime, Input input) override
References GameObject::CollisionPoint, GetMovementArea, Game::GetWindowSize, Input::keyboardState, MouseStateDescriptor::lPressed, GameObject::m_dimensions, GameObject::m_game, GameObject::m_position, m_score, m_scoreText, m_time, Input::mouseState, Game::Quit, SetHighScore, Text::SetText, MouseStateDescriptor::x, MouseStateDescriptor::y.
void SM_Controller::OnCollision(GameObject *collider) override
References GameObject::m_game, m_highScore, GameObject::m_name, m_scoreText, Game::PlaySound, Game::RemoveObject, Game::SetActiveScene, Text::SetText, Game::StopSound, WriteOnFile.
glm::vec2 SM_Controller::GetMovementArea()
References Game::GetWindowSize, GameObject::m_game, m_movX.
Referenced by Update.
void SM_Controller::SetHighScore(int score)
References m_highScore.
Referenced by Update.
int SM_Controller::GetScore()
References m_score.
void SM_Controller::AssignTextScore(Text *text)
References m_scoreText.
Referenced by main.
void SM_Controller::ReadFromFile()
References m_highScore.
Referenced by Start.
void SM_Controller::WriteOnFile(int score)
Referenced by OnCollision.